steps:
  # - name: maven
  #   entrypoint: mvn
  #   args: ["install"]
    
  - name: gcr.io/cloud-builders/docker
    args: [
            "build", 
            "-t", 
            "us-central1-docker.pkg.dev/practice-379412/practice/helloworld:v1",
            "."]

  - name: gcr.io/cloud-builders/docker
    args: [
            "push",
            "us-central1-docker.pkg.dev/practice-379412/practice/helloworld:v1", 
            "."]

images: ["us-central1-docker.pkg.dev/practice-379412/practice/helloworld"]