steps:
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["test"]

  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["package"]
    
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/helloworld", "--build-arg=JAR_FILE=target/hello-world.jar", "."]
images: ["us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/hellospring"]