steps:
  # - name: maven
  #   entrypoint: mvn
  #   args: ["install"]
    
  - name: gcr.io/cloud-builders/docker
    args: [
            "build", 
            "-t", 
            "us-central1-docker.pkg.dev/practice-379412/practice/helloworld:v1",
            "."]

  - name: gcr.io/cloud-builders/docker
    args: [
            "push",
            "us-central1-docker.pkg.dev/practice-379412/practice/helloworld:v1"]

# images: ["us-central1-docker.pkg.dev/practice-379412/practice/helloworld"]

  - name: gcr.io/cloud-builders/gke-deploy
    args:
    - run
    - --filename=deployment.yaml
    - --image=gcr.io/practice-379412/helloworld:v1
    - --location=us-central1
    - --cluster=cluster1