steps:
  - name: maven
    entrypoint: mvn
    args: ["test"]
    
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/helloworld", "--build-arg=JAR_FILE=target/hello-world.jar", "."]
images: ["us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/helloworld"]