steps:
  # - name: maven
  #   entrypoint: mvn
  #   args: ["install"]
    
  - name: gcr.io/cloud-builders/docker
    args: [
            "build", 
            "-t", 
            "us-central1-docker.pkg.dev/practice-379412/practice/helloworld",
            "."]

  - name: gcr.io/cloud-builders/docker
    args: [
            "push", 
            "-t", 
            "us-central1-docker.pkg.dev/practice-379412/practice/helloworld", 
            "."]

images: ["us-central1-docker.pkg.dev/practice-379412/practice/helloworld"]