apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-app
  labels:
    app: practice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice-app
  template:
    metadata:
      labels:
        app: practice-app
    spec:
      containers:
      - name: practice-app
        image: us-central1-docker.pkg.dev/practice-379412/practice/helloworld:v1
        ports:
        - containerPort: 80