apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice_app
labels:
  app: practice_app
spec:
  replicas: 1
  selector:
  matchLabels:
    app: practice_app
  template:
    labels:
      app: practice_app
  spec:
  containers:
  - name: practice_app 
    image: us-central1-docker.pkg.dev/practice-379412/practice/helloworld:v1