apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deployment
lables:
 app: ngnix
spec:
  replicas: 1
  selector:
  matchLabels:
    app: ngnix
  template:
    matadata:
    labels:
      app: ngnix
  spec:
  containers:
  - name: ngnix
    image: ngnix:1.7.9
    ports:
  - containers: 80